const $lunchRoom = document.getElementById('lunchRoom')
const $lunchRoomLink = document.getElementById('lunchRoomLink')
const $weatherReport = document.getElementById('weatherReport')
const $weatherReportLink = document.getElementById('weatherReportLink')
const $story = document.getElementById('story')

const $lrContainer = document.getElementById('lrContainer')
const $lrNoun = document.getElementById('lrNoun')
const $lrAdjective1 = document.getElementById('lrAdjective1')
const $lrAdjective2 = document.getElementById('lrAdjective2')
const $lrVegetable1 = document.getElementById('lrVegetable1')
const $lrVegetable2 = document.getElementById('lrVegetable2')
const $lrAnimal = document.getElementById('lrAnimal')